FROM golang:1.23-alpine
RUN apk add --no-cache gcc musl-dev wget
WORKDIR /app
COPY go.mod go.sum ./
RUN go mod download
COPY internal/ ./internal/
COPY cmd/ ./cmd/
COPY unit_tests/ ./unit_tests/
COPY API_tests/ ./API_tests/
CMD ["go", "test", "./unit_tests/...", "-v", "-count=1"]
