// Code generated by templ - DO NOT EDIT.

// templ: version: v0.2.793
package templates

//lint:file-ignore SA4006 This context is only used if a nested component is present.

import "github.com/a-h/templ"
import templruntime "github.com/a-h/templ/runtime"

func CheckinStatusPage() templ.Component {
	return templruntime.GeneratedTemplate(func(templ_7745c5c3_Input templruntime.GeneratedComponentInput) (templ_7745c5c3_Err error) {
		templ_7745c5c3_W, ctx := templ_7745c5c3_Input.Writer, templ_7745c5c3_Input.Context
		if templ_7745c5c3_CtxErr := ctx.Err(); templ_7745c5c3_CtxErr != nil {
			return templ_7745c5c3_CtxErr
		}
		templ_7745c5c3_Buffer, templ_7745c5c3_IsBuffer := templruntime.GetBuffer(templ_7745c5c3_W)
		if !templ_7745c5c3_IsBuffer {
			defer func() {
				templ_7745c5c3_BufErr := templruntime.ReleaseBuffer(templ_7745c5c3_Buffer)
				if templ_7745c5c3_Err == nil {
					templ_7745c5c3_Err = templ_7745c5c3_BufErr
				}
			}()
		}
		ctx = templ.InitializeContext(ctx)
		templ_7745c5c3_Var1 := templ.GetChildren(ctx)
		if templ_7745c5c3_Var1 == nil {
			templ_7745c5c3_Var1 = templ.NopComponent
		}
		ctx = templ.ClearChildren(ctx)
		templ_7745c5c3_Var2 := templruntime.GeneratedTemplate(func(templ_7745c5c3_Input templruntime.GeneratedComponentInput) (templ_7745c5c3_Err error) {
			templ_7745c5c3_W, ctx := templ_7745c5c3_Input.Writer, templ_7745c5c3_Input.Context
			templ_7745c5c3_Buffer, templ_7745c5c3_IsBuffer := templruntime.GetBuffer(templ_7745c5c3_W)
			if !templ_7745c5c3_IsBuffer {
				defer func() {
					templ_7745c5c3_BufErr := templruntime.ReleaseBuffer(templ_7745c5c3_Buffer)
					if templ_7745c5c3_Err == nil {
						templ_7745c5c3_Err = templ_7745c5c3_BufErr
					}
				}()
			}
			ctx = templ.InitializeContext(ctx)
			_, templ_7745c5c3_Err = templ_7745c5c3_Buffer.WriteString("<div><h1 class=\"text-2xl font-bold text-gray-900 mb-6\">Check-in Status</h1><div id=\"checkin-content\"><div class=\"skeleton h-32 rounded-lg\"></div></div></div><script>\n\t\tasync function loadCheckinStatus() {\n\t\t\tconst el = document.getElementById('checkin-content');\n\t\t\tel.innerHTML = `\n\t\t\t\t<div class=\"bg-white rounded-lg shadow p-6\">\n\t\t\t\t\t<p class=\"text-gray-500\">Check-in status is managed by staff at the facility kiosk.</p>\n\t\t\t\t\t<p class=\"text-sm text-gray-400 mt-2\">Your active check-in details will appear here during a session.</p>\n\t\t\t\t\t<div class=\"mt-4\">\n\t\t\t\t\t\t<h3 class=\"font-medium mb-2\">Waitlist Position</h3>\n\t\t\t\t\t\t<div id=\"waitlist-info\" class=\"text-sm text-gray-600\">Loading...</div>\n\t\t\t\t\t</div>\n\t\t\t\t</div>`;\n\t\t\tconst res = await api('/api/waitlist/position');\n\t\t\tconst wl = document.getElementById('waitlist-info');\n\t\t\tif (res?.data?.position) {\n\t\t\t\twl.innerHTML = `You are #${res.data.position} in the waitlist for session \"${res.data.session_title || 'N/A'}\"`;\n\t\t\t} else {\n\t\t\t\twl.innerHTML = 'You are not currently on any waitlist.';\n\t\t\t}\n\t\t}\n\t\tloadCheckinStatus();\n\t\t</script>")
			if templ_7745c5c3_Err != nil {
				return templ_7745c5c3_Err
			}
			return templ_7745c5c3_Err
		})
		templ_7745c5c3_Err = Base("Check-in", true).Render(templ.WithChildren(ctx, templ_7745c5c3_Var2), templ_7745c5c3_Buffer)
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		return templ_7745c5c3_Err
	})
}

var _ = templruntime.GeneratedTemplate
